var res = {
    HelloWorld_png : "res/HelloWorld.png",
    CloseNormal_png : "res/CloseNormal.png",
    CloseSelected_png : "res/CloseSelected.png",
    boton_jugar_png : "res/boton_jugar.png",
    menu_titulo_png : "res/menu_titulo.png",
    mapa_puzzles : "res/Mapas/Mapa_puzzles/mapa_puzzles.tmx",
    mapa_boss : "res/Mapas/Mapa_boss/mapa_boss.tmx",
    PrtRiver_Boss_png: "res/Mapas/Mapa_boss/PrtRiver_Boss.png",
    PrtRiver_png: "res/Mapas/Mapa_puzzles/PrtRiver.png",
    bkBlue_png: "res/Mapas/Mapa_puzzles/bkBlue.png",
    bkBlue_boss_png: "res/Mapas/Mapa_boss/bkBlue.png",
    moneda_png : "res/moneda.png",
    moneda_plist : "res/moneda.plist",
    disparo_png : "res/disparo.png",
    disparo_plist : "res/disparo.plist",
    animacion_cuervo_png: "res/animacion_cuervo.png",
    animacion_cuervo_plist: "res/animacion_cuervo.plist",
    disparo_jugador_png: "res/Efectos/Disparos/Jugador/disparo_jugador.png",
    disparo_jugador_plist: "res/Efectos/Disparos/Jugador/disparo_jugador.plist",
    walking_plist : "res/Jugador/Caminando/walking.plist",
    walking_png : "res/Jugador/Caminando/walking.png",
    jumping_plist : "res/Jugador/Saltando/jumping.plist",
    jumping_png : "res/Jugador/Saltando/jumping.png",
    dieing_plist : "res/Jugador/Muriendo/dieing.plist",
    dieing_png : "res/Jugador/Muriendo/dieing.png",
    idle_plist : "res/Jugador/Parado/idle.plist",
    idle_png : "res/Jugador/Parado/idle.png",
    corazon_png : "res/Interfaz/Vida/corazon.png",
    fondo_toolbar_png : "res/Interfaz/Fondo/fondoToolBar.png",
    text_0_png : "res/Interfaz/Textos/text_0.png",
    text_1_png : "res/Interfaz/Textos/text_1.png",
    text_2_png : "res/Interfaz/Textos/text_2.png",
    text_3_png : "res/Interfaz/Textos/text_3.png",
    text_4_png : "res/Interfaz/Textos/text_4.png",
    text_5_png : "res/Interfaz/Textos/text_5.png",
    text_6_png : "res/Interfaz/Textos/text_6.png",
    text_7_png : "res/Interfaz/Textos/text_7.png",
    text_8_png : "res/Interfaz/Textos/text_8.png",
    text_9_png : "res/Interfaz/Textos/text_9.png",
    text_air_png : "res/Interfaz/Textos/text_air.png",

};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}