var res = {
    HelloWorld_png : "res/HelloWorld.png",
    CloseNormal_png : "res/CloseNormal.png",
    CloseSelected_png : "res/CloseSelected.png",
    boton_jugar_png : "res/boton_jugar.png",
    menu_titulo_png : "res/menu_titulo.png",
    mapa_puzzles : "res/Mapas/Mapa_puzzles/mapa_puzzles.tmx",
    mapa_boss : "res/Mapas/Mapa_boss/mapa_boss.tmx",
    PrtRiver_Boss_png: "res/Mapas/Mapa_boss/PrtRiver_Boss.png",
    PrtRiver_png: "res/Mapas/Mapa_puzzles/PrtRiver.png",
    bkBlue_png: "res/Mapas/Mapa_puzzles/bkBlue.png",
    bkBlue_boss_png: "res/Mapas/Mapa_boss/bkBlue.png",
    escalera_png : "res/Mapas/Mapa_boss/escalera.png",
    disparo_png : "res/disparo.png",
    disparo_plist : "res/disparo.plist",
    animacion_cuervo_png: "res/animacion_cuervo.png",
    animacion_cuervo_plist: "res/animacion_cuervo.plist",
    disparo_jugador_png: "res/Efectos/Disparos/Jugador/disparo_jugador.png",
    disparo_jugador_plist: "res/Efectos/Disparos/Jugador/disparo_jugador.plist",
    walking_plist : "res/Jugador/Caminando/walking.plist",
    walking_png : "res/Jugador/Caminando/walking.png",
    jumping_plist : "res/Jugador/Saltando/jumping.plist",
    jumping_png : "res/Jugador/Saltando/jumping.png",
    dieing_plist : "res/Jugador/Muriendo/dieing.plist",
    dieing_png : "res/Jugador/Muriendo/dieing.png",
    idle_plist : "res/Jugador/Parado/idle.plist",
    idle_png : "res/Jugador/Parado/idle.png",
    corazon_png : "res/Interfaz/Vida/corazon.png",
    fondo_toolbar_png : "res/Interfaz/Fondo/fondoToolBar.png",
    text_0_png : "res/Interfaz/Textos/text_0.png",
    text_1_png : "res/Interfaz/Textos/text_1.png",
    text_2_png : "res/Interfaz/Textos/text_2.png",
    text_3_png : "res/Interfaz/Textos/text_3.png",
    text_4_png : "res/Interfaz/Textos/text_4.png",
    text_5_png : "res/Interfaz/Textos/text_5.png",
    text_6_png : "res/Interfaz/Textos/text_6.png",
    text_7_png : "res/Interfaz/Textos/text_7.png",
    text_8_png : "res/Interfaz/Textos/text_8.png",
    text_9_png : "res/Interfaz/Textos/text_9.png",
    text1_0_png : "res/Interfaz/Textos/text1_0.png",
    text1_1_png : "res/Interfaz/Textos/text1_1.png",
    text1_2_png : "res/Interfaz/Textos/text1_2.png",
    text1_3_png : "res/Interfaz/Textos/text1_3.png",
    text1_4_png : "res/Interfaz/Textos/text1_4.png",
    text1_5_png : "res/Interfaz/Textos/text1_5.png",
    text1_6_png : "res/Interfaz/Textos/text1_6.png",
    text1_7_png : "res/Interfaz/Textos/text1_7.png",
    text1_8_png : "res/Interfaz/Textos/text1_8.png",
    text1_9_png : "res/Interfaz/Textos/text1_9.png",
    text_air_png : "res/Interfaz/Textos/text_air.png",
    puerta_puzzle_png : "res/ObjetosMapa/Puertas/puerta_puzzle.png",
    contador_0_5_png : "res/ObjetosMapa/Contadores/contador_0_5.png",
    contador_1_5_png : "res/ObjetosMapa/Contadores/contador_1_5.png",
    contador_2_5_png : "res/ObjetosMapa/Contadores/contador_2_5.png",
    contador_3_5_png : "res/ObjetosMapa/Contadores/contador_3_5.png",
    contador_4_5_png : "res/ObjetosMapa/Contadores/contador_4_5.png",
    contador_5_5_png : "res/ObjetosMapa/Contadores/contador_5_5.png",
    caja_objeto_png : "res/Interfaz/Marcos/caja_objeto.png",
    bola_png : "res/ObjetosMapa/Recolectables/bola.png",
    pulsar_raton_png : "res/ObjetosMapa/Raton/pulsarRaton.png",
    soul_plist : "res/ObjetosMapa/Recolectables/soul.plist",
    soul_png : "res/ObjetosMapa/Recolectables/soul.png",
    bala_png: "res/ObjetosMapa/Recolectables/bala.png",
    cajaMonedas_png: "res/ObjetosMapa/Recolectables/cajaMonedas.png",
    moneda_png: "res/ObjetosMapa/Recolectables/moneda.png",
    proteccion_png: "res/ObjetosMapa/Recolectables/proteccion.png",
    invulnerabilidad_png: "res/ObjetosMapa/Recolectables/invulnerabilidad.png",
    vida_png: "res/ObjetosMapa/Recolectables/vida.png",
    llave_png: "res/ObjetosMapa/Recolectables/llave.png",
    salto_png : "res/ObjetosMapa/Recolectables/salto.png",
    soul_individual_png : "res/Interfaz/Objetos/soul.png",
    relleno_png : "res/Interfaz/Fondo/relleno.png",
    fantasma_plist : "res/Enemigos/fantasma.plist",
    fantasma_png : "res/Enemigos/fantasma.png",
    volador_plist : "res/Enemigos/volador.plist",
    volador_png : "res/Enemigos/volador.png",
    terrestre_plist : "res/Enemigos/terrestre.plist",
    terrestre_png : "res/Enemigos/terrestre.png",
    boss_plist : "res/Enemigos/boss.plist",
    boss_png : "res/Enemigos/boss.png",
    disparo_boss_plist : "res/Enemigos/Efectos/disparo_boss.plist",
    disparo_boss_png : "res/Enemigos/Efectos/disparo_boss.png",
    disparo_enemigo_plist: "res/Enemigos/Efectos/disparo_enemigo.plist",
    disparo_enemigo_png : "res/Enemigos/Efectos/disparo_enemigo.png",


};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}